#!/bin/bash
# shellcheck disable=SC2012,SC2181

################################################################################

# Database host (String)
PG_HOST="${DB_HOST:-127.0.0.1}"

# Database user name (String)
PG_USER="${DB_USER:-mmuser}"

# Database user password (String)
PG_PASS="${DB_PASS}"

# Name of Mattermost database (String)
PG_DB="${DB_NAME:-mattermost}"

# Path to directory with Mattermost data (String)
MM_DATA="${DATA_DIR:-/srv/mattermost-data}"

# Path to directory with Mattermost server (String)
MM_SERVER="${SERVER_DIR:-/srv/mattermost}"

# Path to directory with backups (String)
BACKUP_DIR="${BACKUP_DIR:-/var/backup}"

# Retention in days (Number)
RETENTION=${RETENTION:-90}

################################################################################

backup_dir=""
full_backup=""

################################################################################

# Main handler
#
# Code: No
# Echo: No
main() {
  if [[ "$1" == "full" ]] ; then
    full_backup=true
  fi

  check

  log "Starting backup process…"

  createBackupDir
  backupDB
  backupData

  if [[ -n "$full_backup" ]] ; then
    backupServer
  fi

  log "Backup successfully complete"
}

# Check preferencies
#
# Code: No
# Echo: No
check() {
  if [[ -z "$PG_HOST" ]] ; then
    log "(ERROR) DB host is empty"
    exit 1
  fi

  if [[ -z "$PG_USER" ]] ; then
    log "(ERROR) DB user is empty"
    exit 1
  fi

  if [[ -z "$PG_PASS" ]] ; then
    log "(ERROR) DB password is empty"
    exit 1
  fi

  if [[ -z "$PG_DB" ]] ; then
    log "(ERROR) DB name is empty"
    exit 1
  fi

  if [[ -z "$MM_DATA" ]] ; then
    log "(ERROR) Path to Mattermost data directory is empty"
    exit 1
  fi

  if [[ -z "$MM_SERVER" ]] ; then
    log "(ERROR) Path to Mattermost server directory is empty"
    exit 1
  fi

  if [[ ! -r "$MM_DATA" ]] ; then
    log "(ERROR) Directory $MM_DATA is not readable"
    exit 1
  fi

  if [[ ! -r "$MM_SERVER" ]] ; then
    log "(ERROR) Directory $MM_SERVER is not readable"
    exit 1
  fi

  if [[ ! -w "$BACKUP_DIR" ]] ; then
    log "(ERROR) Directory $BACKUP_DIR is not writable"
    exit 1
  fi

  if ! type -P xz &> /dev/null ; then
    log "(ERROR) xz is required"
    exit 1
  fi

  if ! type -P pg_dump &> /dev/null ; then
    log "(ERROR) pg_dump is required"
    exit 1
  fi
}

# Create directory for backups
#
# Code: No
# Echo: No
createBackupDir() {
  local backup_date

  backup_date=$(date '+%Y-%m-%d-%H%M')
  backup_dir="${BACKUP_DIR}/${backup_date}"

  if ! mkdir "${backup_dir}" &> /dev/null ; then
    log "(ERROR) Can't create directory for backup"
    exit 1
  fi
}

# Create xz archive with database dump
#
# Code: No
# Echo: No
backupDB() {
  local output output_size

  log "Backuping database…"

  export PGPASSWORD="$PG_PASS"

  output="${backup_dir}/database.xz"

  pg_dump -h "$PG_HOST" -U "$PG_USER" "$PG_DB" | xz -4 > "$output"

  if [[ $? -ne 0 ]] ; then
    log "(ERROR) Can't create database backup"
    export PGPASSWORD=""
    return
  fi

  export PGPASSWORD=""
  chmod 600 "$output"

  output_size=$(ls -lah "$output" | awk -F " " '{print $5}')

  log "Database backup successfully created (size: $output_size)"
}

# Create xz archive with server data
#
# Code: No
# Echo: No
backupData() {
  local output output_size dir_parent dir_target

  log "Backuping data…"

  output="${backup_dir}/data.txz"
  dir_parent=$(dirname "$MM_DATA")
  dir_target=$(basename "$MM_DATA")

  tar -C "${dir_parent}" -cf - "$dir_target" | xz -1 -z - > "$output"

  if [[ $? -ne 0 ]] ; then
    log "(ERROR) Can't create data backup"
    return
  fi

  chmod 600 "$output"

  output_size=$(ls -lah "$output" | awk -F " " '{print $5}')

  log "Data backup successfully created (size: $output_size)"
}

# Create xz archive with server installation directory
#
# Code: No
# Echo: No
backupServer() {
  local output output_size dir_parent dir_target

  log "Backuping server…"

  output="${backup_dir}/server.txz"
  dir_parent=$(dirname "$MM_SERVER")
  dir_target=$(basename "$MM_SERVER")

  tar -C "${dir_parent}" \
      --exclude="${dir_target}/logs" \
      --exclude="${dir_target}/prepackaged_plugins" \
      -cf - "$dir_target" | xz -1 -z - > "$output"

  if [[ $? -ne 0 ]] ; then
    log "(ERROR) Can't create server backup"
    return
  fi

  chmod 600 "$output"

  output_size=$(ls -lah "$output" | awk -F " " '{print $5}')

  log "Server backup successfully created (size: $output_size)"
}

# Print message to log file
#
# 1: Log message (String)
#
# Code: No
# Echo: No
log() {
  echo "$(date '+[ %Y/%m/%d %H:%M:%S.%3N ]') $*"
}

################################################################################

main "$@"
